### ISSUE TITLE
Overzealous supplementary rule? "Gemini2-mi17-refSysInfo-recs"

### ISSUE THREAD

**Issue by PeterParslow** [AGIGemini/Schematron#3]
This rule fires for any SRS that isn't in the INSPIRE default list. Perhaps it should only check the first one?

In fact, perhaps that's what the [1]s are trying to achieve?

Should the context in line 57, "//gmd:MD_Metadata[1]/gmd:referenceSystemInfo/*[1]/gmd:referenceSystemIdentifier/gmd:RS_Identifier[1]/gmd:code/gmx:Anchor[1]/@xlink:href", actually be "//gmd:MD_Metadata[1]/gmd:referenceSystemInfo[1]/*/gmd:referenceSystemIdentifier/gmd:RS_Identifier[1]/gmd:code/gmx:Anchor[1]/@xlink:href"

(& even the other [1]s be on the roles, not the objects?)

Also (so perhaps a second issues), surely INSPIRE TG Requirement 2.2: metadata/2.0/req/isdss/crs-id states that the default CRSs shall be in the text of the element, 

So perhaps this rule should move to the other Schematron file? But only if it's generalised to check the text regardless of whether it's an Anchor or a CharacterString, i.e. 4a in that harder rule would check gmx:Anchor not gmx:Anchor/@xlink:href

See discussion mainly in Bug Tracker Google doc

**Comment by archaeogeek** [comment]
Closed in favour of https://github.com/agiorguk/gemini-schematron/issues/4.
