### ISSUE TITLE
Over zealous MI-38 coupled resource check

### ISSUE THREAD

**Issue by PeterParslow** [AGIGemini/Schematron#7]
_Coupled resource_ is "Conditional - mandatory for View and Download services, optional for other service types."

The Schematron rule seems to make it mandatory.

I ran across this years back when making the one national record for the National Discovery Service. I've now hit it again when trying to create on for our new OS CSW.

**Comment by nmtoken** [comment]
<sch:pattern fpi="Gemini2-mi38">
        <sch:title>Coupled resource</sch:title>
        <sch:rule context="//gmd:MD_Metadata[1]/gmd:identificationInfo[1]/*[1]/srv:operatesOn">
          <sch:assert test="count(@xlink:href) = 1"> MI-38 (Coupled Resource): Coupled resource shall be implemented by
            reference using the xlink:href attribute. </sch:assert>
        </sch:rule>
      </sch:pattern>

Rule doesn't mandate srv:operatesOn just says that where one exists you must use xlink:href.  It is attempting to apply the last paragraph of TG requirement 3.6

> TG Requirement 3.6: metadata/2.0/req/sds/coupled-resource
> Links pointing to the online metadata descriptions of data sets provided by the described service shall be given using srv:operatesOn element.

> The multiplicity of this element is 0..n.

> This property shall be implemented by reference. The xlink:href attribute of each of the srv:operatesOn elements shall contain a URI pointing to the gmd:MD_DataIdentification element of the metadata record of the provided the data set or data set series.

**Comment by PeterParslow** [comment]
Ah, I hit a GeoNetwork behaviour. The template contains an empty  <srv:operatesOn/> (in order that the opportunity to create one exists in the GUI, I think), and it is that which fails. Delete it (in XML view) and I pass validation.

Given that Discovery Service records will be pretty rare, I can live with that.

**Comment by archaeogeek** [comment]
Good catch @PeterParslow I can improve this behaviour in GeoNetwork/Gemini. Yes, we need a blank entry in the template to allow users to easily create a new one when editing, but we can (and do with other elements) clean up these blank entries on validation/save. I'll create an issue for this in the Gemini project, though it might be a while before I get to it!
